name: Online Competition

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:


jobs:
  online-competition:
    # Skip this job if running on the main repo to prevent failing CI/CD. Only run on student forks.
    if: ${{ github.repository != 'utiasDSL/lsy_drone_racing' }}

    runs-on: ubuntu-latest
    env: # Or as an environment variable
      KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
      KAGGLE_KEY: ${{ secrets.KaggleKey }}

    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.1.0-0' # any version from https://github.com/mamba-org/micromamba-releases
          environment-name: test-env
          init-shell: bash
          create-args: python=3.12
          cache-environment: true
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
      - name: Install acados from source
        run: |
          cd $HOME
          git clone https://github.com/acados/acados.git
          cd acados
          git checkout tags/v0.5.0
          git submodule update --recursive --init
          
          mkdir -p build
          cd build
          cmake -DACADOS_WITH_QPOASES=ON ..
          make install -j4
          
          # Install Python interface
          cd $HOME/acados
          pip install -e interfaces/acados_template
      - name: Set environment variables
        run: |
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/acados/lib" >> $GITHUB_ENV
          echo "ACADOS_SOURCE_DIR=$HOME/acados" >> $GITHUB_ENV
      - run: pip install .[online_submission,test]
        shell: micromamba-shell {0}
      - name: Run simulation tests
        run: python scripts/kaggle.py
        shell: micromamba-shell {0}
      - name: Export with kaggle
        run: kaggle competitions submit -c lsy-drone-racing-ss-25 -f submission.csv -m "Automated submission"
        shell: micromamba-shell {0}
